export const books = [
  {
    id: 1,
    title: "Norwegian Wood",
    author: "Haruki Murakami",
    quantity: 10,
  },
  {
    id: 2,
    title: "The Satsuma Complex",
    author: " Bob Mortimer",
    quantity: 3,
  },
  {
    id: 3,
    title: "Possibility of an Island",
    author: "Michel Houellebecq",
    quantity: 7,
  },
  {
    id: 4,
    title: "Gideon the Ninth",
    author: "Tamsyn Muir",
    quantity: 6,
  },
  {
    id: 5,
    title: "The Atrocity Exhibition",
    author: "J. G. Ballard",
    quantity: 8,
  },
  {
    id: 6,
    title: "Gearbreakers",
    author: "Zoe Hana Mikuta",
    quantity: 2,
  },
  {
    id: 7,
    title: "Berserk",
    author: "Kentaro Miura",
    quantity: 4,
  },
  {
    id: 8,
    title: "Roadside Picnic",
    author: "Arkady and Boris Strugatsky",
    quantity: 9,
  },
  {
    id: 9,
    title: "House of Leaves",
    author: "Mark Danielewski",
    quantity: 1,
  },
  {
    id: 10,
    title: "Bad Blood",
    author: "John Carreyrou",
    quantity: 5,
  },
  {
    id: 11,
    title: "On the Move: A Life",
    author: "Oliver Sacks",
    quantity: 7,
  },
  {
    id: 12,
    title: "The Fellowship of the Ring",
    author: "J.R.R Tolkien",
    quantity: 6,
  },
  {
    id: 13,
    title: "The Two Towers",
    author: "J.R.R Tolkien",
    quantity: 5,
  },
  {
    id: 14,
    title: "The Return of the King",
    author: "J.R.R Tolkien",
    quantity: 3,
  },
  {
    id: 15,
    title: "The Skystone",
    author: "Jack Whyte",
    quantity: 4,
  },
];