export const books = [
  {
    id: 1,
    title: "Around the World in Eighty Days",
    author: "Jules Verne",
    quantity: 10,
  },
  {
    id: 2,
    title: "To Kill a Mockingbird",
    author: "Harper Lee",
    quantity: 3,
  },
  {
    id: 3,
    title: "1984",
    author: "George Orwell",
    quantity: 7,
  },
  {
    id: 4,
    title: "Moby Dick",
    author: "Herman Melville",
    quantity: 6,
  },
  {
    id: 5,
    title: "Pride and Prejudice",
    author: "Jane Austen",
    quantity: 8,
  },
  {
    id: 6,
    title: "The Great Gatsby",
    author: "F. Scott Fitzgerald",
    quantity: 2,
  },
  {
    id: 7,
    title: "War and Peace",
    author: "Leo Tolstoy",
    quantity: 4,
  },
  {
    id: 8,
    title: "The Catcher in the Rye",
    author: "J.D. Salinger",
    quantity: 9,
  },
  {
    id: 9,
    title: "Ulysses",
    author: "James Joyce",
    quantity: 1,
  },
  {
    id: 10,
    title: "The Hobbit",
    author: "J.R.R. Tolkien",
    quantity: 5,
  },
  {
    id: 11,
    title: "Don Quixote",
    author: "Miguel de Cervantes",
    quantity: 7,
  },
  {
    id: 12,
    title: "One Hundred Years of Solitude",
    author: "Gabriel García Márquez",
    quantity: 6,
  },
  {
    id: 13,
    title: "The Old Man and the Sea",
    author: "Ernest Hemingway",
    quantity: 5,
  },
  {
    id: 14,
    title: "Anna Karenina",
    author: "Leo Tolstoy",
    quantity: 3,
  },
  {
    id: 15,
    title: "Les Misérables",
    author: "Victor Hugo",
    quantity: 4,
  },
];
